- path : path/to/scala/files1
  outputFile : xx1.md
  tokenizer : default
  filters :
    includes :
      - regex1
      - regex2
    excludes :
      - regex1
      - regex2
    contains :
      - regex1
      - regex2
  display :
    fields : false
    methods : false
    constructors : false
    innerClasses : false
    dependencies : false
- path : path/to/scala/files2
  outputFile : xx1.md
  tokenizer : default
  filters :
    includes :
      - regex1
      - regex2
    excludes :
      - regex1
      - regex2
    contains :
      - regex1
      - regex2
  display :
    fields : false
    methods : false
    constructors : false
    innerClasses : false
    dependencies : false
